#include <iostream>
using namespace std;

int main() 
    {
    
     cout<<"EJERCICIO 26...."<<endl;
        cout<<"Un gigante de otro planeta ,durante su visita utiliza una mascara."<<endl;
        cout<<"Su mascara mide de altura 14.3 y de base 6.4. "<<endl;
     double b,h;
       cout<<"base 6.4 "<<endl;
        b=6.4;
        cout<<"altura 14.3 "<<endl;
        h=14.3;
        double area;
        area=b*h/2;
        cout<<"Metros Cuadrados que necesita el gigante  " <<area<<endl;
      return 0;
    }
