#include <iostream>
#include <math.h>
using namespace std;

int main() 
    {
        double A,B,C;
        cout<<"....PERIMETRO DE UN TRIANGULO RECTANGULO..."<<endl;
        cin>>A;
        cin>>B; 
        cout<<"CATETO A: "<<A<<endl;
        cout<<"CATETO B: "<<B<<endl;
        C=sqrt((A*A+B*B));
        cout<<"HIPOTENUSA C: "<<C<<endl;
        double Perimetro;
        Perimetro=A+B+C;
        cout<<"PERIMETRO :"<<Perimetro<<endl;
        
	return 0;
}
