#include <iostream>
#include <math.h>
using namespace std;

int main()  
    {
        double A,B,C;
        cout<<"....PERIMETRO DE UN TRIANGULO RECTANGULO..."<<endl;
        cin>>A;
        cin>>C; 
        cout<<"CATETO A: "<<A<<endl;
        cout<<"HIPOTENUSA B: "<<C<<endl;
        B=sqrt((C*C-A*A));
        cout<<"CATETO B: "<<B<<endl;
        double Perimetro;
        Perimetro=A+B+C;
        cout<<"PERIMETRO :"<<Perimetro<<endl;
        
    	return 0;
    }
